[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Shopify App Routes (all under /shopapp)
[[redirects]]
  from = "/shopapp/auth"
  to = "/.netlify/functions/auth"
  status = 200
  force = true

[[redirects]]
  from = "/shopapp/auth/callback"
  to = "/.netlify/functions/auth-callback"
  status = 200
  force = true

[[redirects]]
  from = "/shopapp/webhooks/app-uninstalled"
  to = "/.netlify/functions/app-uninstalled"
  status = 200
  force = true

[[redirects]]
  from = "/shopapp/webhooks/app-scopes-update"
  to = "/.netlify/functions/app-scopes-update"
  status = 200
  force = true

[[redirects]]
  from = "/shopapp/welcome"
  to = "/.netlify/functions/welcome"
  status = 200
  force = true

# Storefront Routes (everything else goes to Remix)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
